(function(){'use strict';
 if(window.__VELORA_STAGE23_LOADED)return;window.__VELORA_STAGE23_LOADED=true;
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function rpc(fn,args={}){if(typeof window.veloraRPC==='function')return window.veloraRPC(fn,args);if(typeof window.callRpc==='function')return window.callRpc(fn,args);if(window.mahaSupabase){const {data,error}=await window.mahaSupabase.rpc(fn,args);if(error)throw error;return data}throw new Error('Supabase RPC bridge unavailable')}
 function statusMarkup(s){s=String(s||'pending');const cls=s==='pass'?'velora-rel-pass':s==='warn'?'velora-rel-warn':(s==='fail'?'velora-rel-fail':(s==='blocked'?'velora-rel-block':''));return `<span class="${cls}">${esc(s.toUpperCase())}</span>`}
 async function render(){
  const c=document.getElementById('adminContent');if(!c)return;c.innerHTML='<div class="velora-pay-note">⏳ Loading release control plane…</div>';
  try{
   const d=await rpc('velora_get_release_control_plane',{}), r=d?.latest_release||null;
   c.innerHTML=`<div class="velora-rel-toolbar"><div><b>Stage 23 — Release Engineering & Change Control</b><div class="velora-rel-muted">Release candidates, approval state, deployment evidence and rollback checkpoints. This layer governs changes; it does not deploy code by itself.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" onclick="window.VELORA_CREATE_RELEASE_UI()">＋ Create candidate</button><button class="btn" onclick="window.VELORA_RENDER_RELEASES()">↻ Refresh</button></div></div>
   <div class="velora-rel-grid"><div class="velora-rel-card"><div>Release Candidates</div><div class="velora-rel-kpi">${esc(d?.release_count??0)}</div><div class="velora-rel-muted">Recorded releases</div></div><div class="velora-rel-card"><div>Governance State</div><div class="velora-rel-kpi">${esc(String(d?.governance_state||'—').replaceAll('_',' ').toUpperCase())}</div><div class="velora-rel-muted">Latest release decision</div></div><div class="velora-rel-card"><div>Checks</div><div class="velora-rel-kpi">${esc(d?.latest_check_count??0)}</div><div class="velora-rel-muted">Latest release checks</div></div><div class="velora-rel-card"><div>Blockers</div><div class="velora-rel-kpi">${esc(d?.latest_blockers??0)}</div><div class="velora-rel-muted">Fail / blocked checks</div></div></div>
   <div class="velora-rel-card"><h3>📦 Latest Release</h3>${r?`<div class="velora-rel-row"><div><b>${esc(r.version)}</b> <span class="velora-rel-chip">${esc(r.environment)}</span><span class="velora-rel-chip">${esc(r.risk_level)}</span><span class="velora-rel-chip">${esc(r.status)}</span><div class="velora-rel-muted" style="margin-top:5px">${esc(r.change_summary)}</div><div class="velora-rel-muted" style="margin-top:4px">Created ${esc(new Date(r.created_at).toLocaleString())} ${r.deployed_at?'· Deployed '+esc(new Date(r.deployed_at).toLocaleString()):''}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" onclick="window.VELORA_SET_RELEASE_STATUS('${esc(r.id)}','approved')">Approve</button><button class="btn btn-primary" onclick="window.VELORA_SET_RELEASE_STATUS('${esc(r.id)}','deployed')">Mark deployed</button><button class="btn" onclick="window.VELORA_SET_RELEASE_STATUS('${esc(r.id)}','rolled_back')">Rollback</button></div></div><div class="velora-rel-muted" style="margin-top:10px"><b>Rollback plan:</b> ${esc(r.rollback_plan||'Not provided')} ${r.rollback_checkpoint?'<br><b>Checkpoint:</b> '+esc(r.rollback_checkpoint):''}</div>`:'<div class="velora-rel-muted">No release candidate exists yet.</div>'}</div>
   <div class="velora-rel-card" style="margin-top:12px"><h3>🧭 Release Discipline</h3><div class="velora-rel-muted">Every production change should have a version, risk level, owner, rollback plan and explicit release checks before deployment. External CI/CD, secrets and hosting deployment remain outside this HTML control plane.</div></div>`;
  }catch(e){c.innerHTML=`<div class="velora-pay-note">❌ Release control plane unavailable: ${esc(e.message||e)}</div>`}
 }
 window.VELORA_CREATE_RELEASE_UI=async function(){
  const version=prompt('Release version (example: 0.23.0)','0.23.0'); if(!version)return;
  const summary=prompt('Change summary','Velora release candidate'); if(!summary)return;
  const risk=(prompt('Risk level: low / medium / high / critical','medium')||'medium').toLowerCase();
  const rollback=prompt('Rollback plan','Restore previous deployed version and verify Launch Console + E2E suite.'); if(!rollback)return;
  try{await rpc('velora_create_release_candidate',{p_version:version,p_environment:'production',p_change_summary:summary,p_risk_level:risk,p_rollback_plan:rollback});await render();alert('Release candidate created. Add evidence/checks before deployment.')}catch(e){alert(e.message||String(e))}
 };
 window.VELORA_SET_RELEASE_STATUS=async function(id,status){
  try{const cp=status==='rolled_back'?'Use the last verified deployment checkpoint.':null;await rpc('velora_update_release_status',{p_release_id:id,p_status:status,p_checkpoint:cp});await render()}catch(e){alert(e.message||String(e))}
 };
 window.VELORA_RENDER_RELEASES=render;
 function addNav(){const nav=document.querySelector('#adminPlatform .admin-nav');if(!nav||nav.querySelector('[data-velora-release-nav]'))return;const sec=document.createElement('div');sec.className='admin-nav-section';sec.innerHTML='<div class="admin-nav-title">Delivery</div><div class="admin-nav-item" data-velora-release-nav="1"><span>📦</span><span>Release Control</span></div>';const item=sec.querySelector('[data-velora-release-nav]');item.onclick=()=>window.VELORA_CANONICAL_ADMIN_SECTION('releaseControl',item);nav.appendChild(sec)}
 const prev=window.VELORA_CANONICAL_ADMIN_SECTION;window.VELORA_CANONICAL_ADMIN_SECTION=async function(section,btn){if(section==='releaseControl'){document.querySelectorAll('.admin-nav-item').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const h=document.getElementById('adminHeaderTitle');if(h)h.textContent='Release Control';return render()}return prev?prev(section,btn):undefined};
 const oldOpen=window.VELORA_OPEN_ADMIN;window.VELORA_OPEN_ADMIN=async function(){const r=oldOpen?await oldOpen():undefined;setTimeout(addNav,350);return r};setTimeout(addNav,1900);
 console.log('✅ Velora Stage 23 Release Engineering & Change Control loaded');
})();
