(function(){'use strict';
 if(window.__VELORA_STAGE21_LOADED)return;window.__VELORA_STAGE21_LOADED=true;
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function rpc(fn,args={}){if(typeof window.veloraRPC==='function')return window.veloraRPC(fn,args);if(typeof window.callRpc==='function')return window.callRpc(fn,args);throw new Error('Supabase RPC bridge unavailable')}
 function mark(status){return status==='pass'?'<span class="velora-audit-pass">PASS</span>':status==='warn'?'<span class="velora-audit-warn">WARN</span>':'<span class="velora-audit-fail">FAIL</span>'}
 async function render(){
  const c=document.getElementById('adminContent');if(!c)return;c.innerHTML='<div class="velora-pay-note">⏳ Running Security Attack Surface Audit…</div>';
  try{const d=await rpc('velora_get_security_attack_surface_audit',{});const checks=Array.isArray(d?.checks)?d.checks:[];
   const pass=checks.filter(x=>x.status==='pass').length,warn=checks.filter(x=>x.status==='warn').length,fail=checks.filter(x=>x.status==='fail').length;
   c.innerHTML=`<div class="velora-audit-toolbar"><div><b>Stage 21 — Security Attack Surface Audit</b><div class="velora-audit-muted">Read-only audit of RLS coverage, exposed RPC privileges, security-definer posture, policy coverage and privileged-surface isolation. No data mutations are performed.</div></div><div class="velora-audit-actions"><button class="btn btn-primary" onclick="window.VELORA_RUN_SECURITY_AUDIT()">🛡️ Run audit</button><button class="btn" onclick="window.VELORA_RENDER_SECURITY_AUDIT()">↻ Refresh</button></div></div>
   <div class="velora-audit-grid"><div class="velora-audit-card"><div>Audit Score</div><div class="velora-audit-kpi">${esc(d?.score??'—')}</div><div class="velora-audit-muted">derived from control checks</div></div><div class="velora-audit-card"><div>Passed</div><div class="velora-audit-kpi velora-audit-pass">${pass}</div><div class="velora-audit-muted">controls satisfied</div></div><div class="velora-audit-card"><div>Warnings</div><div class="velora-audit-kpi velora-audit-warn">${warn}</div><div class="velora-audit-muted">review before go-live</div></div><div class="velora-audit-card"><div>Failures</div><div class="velora-audit-kpi velora-audit-fail">${fail}</div><div class="velora-audit-muted">must be remediated</div></div></div>
   <div class="velora-audit-card"><h3>🔍 Attack Surface Checks</h3>${checks.length?checks.map(x=>`<div class="velora-audit-row"><div><b>${esc(x.control_name)}</b><div class="velora-audit-muted">${esc(x.control_code||'')}</div><div class="velora-audit-muted">${esc(x.message||'')}</div></div><div>${mark(x.status)}</div></div>`).join(''):'<div class="velora-audit-muted">No checks returned.</div>'}</div>
   <div class="velora-audit-card" style="margin-top:12px"><h3>🔐 Security Boundaries</h3><div class="velora-audit-note">This audit intentionally does not attempt exploit traffic or destructive penetration testing. It validates database-side exposure and privilege boundaries. External provider security, CDN/WAF configuration, hosting headers, secret rotation and production infrastructure still require environment-level review.</div></div>`;
  }catch(e){c.innerHTML=`<div class="velora-pay-note">❌ Security audit unavailable: ${esc(e.message||e)}</div>`}
 }
 window.VELORA_RUN_SECURITY_AUDIT=async function(){try{await rpc('velora_run_security_attack_surface_audit',{});await render()}catch(e){alert(e.message||String(e))}};
 window.VELORA_RENDER_SECURITY_AUDIT=render;
 function addNav(){const nav=document.querySelector('#adminPlatform .admin-nav');if(!nav||nav.querySelector('[data-velora-sec-audit-nav]'))return;const sec=document.createElement('div');sec.className='admin-nav-section';sec.innerHTML='<div class="admin-nav-title">Security</div><div class="admin-nav-item" data-velora-sec-audit-nav="1"><span>🛡️</span><span>Attack Surface Audit</span></div>';const item=sec.querySelector('[data-velora-sec-audit-nav]');item.onclick=()=>window.VELORA_CANONICAL_ADMIN_SECTION('securityAudit',item);nav.appendChild(sec)}
 const prev=window.VELORA_CANONICAL_ADMIN_SECTION;window.VELORA_CANONICAL_ADMIN_SECTION=async function(section,btn){if(section==='securityAudit'){document.querySelectorAll('.admin-nav-item').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const h=document.getElementById('adminHeaderTitle');if(h)h.textContent='Attack Surface Audit';return render()}return prev?prev(section,btn):undefined};
 const oldOpen=window.VELORA_OPEN_ADMIN;window.VELORA_OPEN_ADMIN=async function(){const r=oldOpen?await oldOpen():undefined;setTimeout(addNav,350);return r};setTimeout(addNav,1800);
 console.log('✅ Velora Stage 21 Security Attack Surface Audit loaded');
})();
