(function(){'use strict';
 if(window.__VELORA_STAGE25_LOADED)return;window.__VELORA_STAGE25_LOADED=true;
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 async function rpc(fn,args={}){if(typeof window.veloraRPC==='function')return window.veloraRPC(fn,args);if(typeof window.callRpc==='function')return window.callRpc(fn,args);throw new Error('Supabase RPC bridge unavailable')}
 function statusHtml(status){return status==='pass'?'<span class="velora-obs-pass">PASS</span>':status==='warn'?'<span class="velora-obs-warn">WARN</span>':'<span class="velora-obs-block">BLOCKED</span>'}
 async function render(){
  const c=document.getElementById('adminContent');if(!c)return;c.innerHTML='<div class="velora-pay-note">⏳ Loading Observability & SLO Engine…</div>';
  try{const d=await rpc('velora_get_observability_control_plane',{});const run=d?.latest_run||null;const ms=Array.isArray(d?.measurements)?d.measurements:[];
   const pass=ms.filter(x=>x.status==='pass').length,warn=ms.filter(x=>x.status==='warn').length,blocked=ms.filter(x=>x.status==='blocked').length;
   c.innerHTML=`<div class="velora-obs-toolbar"><div><b>Stage 25 — Observability & SLO Engine</b><div class="velora-obs-muted">Database-backed operational signals, SLO governance and explicit telemetry gaps. This layer does not pretend to measure infrastructure latency that has not been instrumented.</div></div><div class="velora-obs-actions"><button class="btn btn-primary" onclick="window.VELORA_RUN_OBSERVABILITY()">📈 Capture snapshot</button><button class="btn" onclick="window.VELORA_RENDER_OBSERVABILITY()">↻ Refresh</button></div></div>
   <div class="velora-obs-grid"><div class="velora-obs-card"><div>Last Snapshot</div><div class="velora-obs-kpi">${run?esc(new Date(run.started_at).toLocaleTimeString()):'—'}</div><div class="velora-obs-muted">${run?esc(run.status):'No snapshot yet'}</div></div><div class="velora-obs-card"><div>Healthy Signals</div><div class="velora-obs-kpi velora-obs-pass">${pass}</div><div class="velora-obs-muted">observability controls</div></div><div class="velora-obs-card"><div>Warnings</div><div class="velora-obs-kpi velora-obs-warn">${warn}</div><div class="velora-obs-muted">needs investigation</div></div><div class="velora-obs-card"><div>Telemetry Blocks</div><div class="velora-obs-kpi velora-obs-block">${blocked}</div><div class="velora-obs-muted">environment instrumentation required</div></div></div>
   <div class="velora-obs-card"><h3>📊 Observability Signals</h3>${ms.length?ms.map(x=>`<div class="velora-obs-row"><div><b>${esc(x.metric_name)}</b><div class="velora-obs-muted">${esc(x.metric_code||'')} · ${esc(x.unit||'')}</div><div class="velora-obs-muted">${esc(x.message||'')}</div></div><div style="text-align:right"><div>${statusHtml(x.status)}</div><div class="velora-obs-muted">${x.metric_value==null?'—':esc(x.metric_value)}</div></div></div>`).join(''):'<div class="velora-obs-muted">No measurements yet.</div>'}</div>
   <div class="velora-obs-card" style="margin-top:12px"><h3>🎯 SLO Contract</h3><div class="velora-obs-note"><b>Availability:</b> requires verified request/response telemetry.<br><b>Latency:</b> requires edge/API latency instrumentation.<br><b>Error Budget:</b> must be calculated from production request/error/latency data.<br><b>Current posture:</b> Velora records database-side operational signals while keeping infrastructure-level SLOs explicitly BLOCKED until real telemetry is connected.</div></div>`;
  }catch(e){c.innerHTML=`<div class="velora-pay-note">❌ Observability engine unavailable: ${esc(e.message||e)}</div>`}
 }
 window.VELORA_RUN_OBSERVABILITY=async function(){try{await rpc('velora_run_observability_snapshot',{});await render()}catch(e){alert(e.message||String(e))}};
 window.VELORA_RENDER_OBSERVABILITY=render;
 function addNav(){const nav=document.querySelector('#adminPlatform .admin-nav');if(!nav||nav.querySelector('[data-velora-obs-nav]'))return;const sec=document.createElement('div');sec.className='admin-nav-section';sec.innerHTML='<div class="admin-nav-title">Observability</div><div class="admin-nav-item" data-velora-obs-nav="1"><span>📈</span><span>Observability & SLO</span></div>';const item=sec.querySelector('[data-velora-obs-nav]');item.onclick=()=>window.VELORA_CANONICAL_ADMIN_SECTION('observability',item);nav.appendChild(sec)}
 const prev=window.VELORA_CANONICAL_ADMIN_SECTION;window.VELORA_CANONICAL_ADMIN_SECTION=async function(section,btn){if(section==='observability'){document.querySelectorAll('.admin-nav-item').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const h=document.getElementById('adminHeaderTitle');if(h)h.textContent='Observability & SLO';return render()}return prev?prev(section,btn):undefined};
 const oldOpen=window.VELORA_OPEN_ADMIN;window.VELORA_OPEN_ADMIN=async function(){const r=oldOpen?await oldOpen():undefined;setTimeout(addNav,350);return r};setTimeout(addNav,1800);
 console.log('✅ Velora Stage 25 Observability & SLO Engine loaded');
})();
