(()=>{
'use strict';
const esc48=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const rpc48=async(name,args={})=>{const c=window.supabaseClient||window.sb;if(!c?.rpc)throw new Error('Supabase client unavailable');return await c.rpc(name,args)};
const host48=()=>document.getElementById('veloraConsolidation48');
const pill48=(v,c='')=>'<span class="velora-con48-pill '+c+'">'+esc48(v||'—')+'</span>';
async function render48(){const h=host48();if(!h)return;h.innerHTML='<div class="velora-con48-card">Running system consolidation audit…</div>';try{let r=await rpc48('velora_get_system_consolidation_audit',{});if(r.error)throw new Error(r.error.message||'Audit unavailable');let d=r.data||{};let s=d.summary||{};let f=Array.isArray(d.findings)?d.findings:[];h.innerHTML='<div class="velora-con48"><div class="velora-con48-toolbar"><div><b>Stage 48 — System Integration Audit & Consolidation</b><div class="velora-con48-muted">A single architecture checkpoint for the accumulated Velora control planes. Read-only audit; no destructive consolidation occurs automatically.</div></div><div class="velora-con48-actions"><button class="velora-con48-btn primary" id="con48Run">▶ Run audit</button><button class="velora-con48-btn" id="con48Refresh">↻ Refresh</button></div></div><div class="velora-con48-grid" style="margin-top:12px"><div class="velora-con48-card"><div class="velora-con48-muted">Score</div><div class="velora-con48-big">'+esc48(d.score??0)+'</div></div><div class="velora-con48-card"><div class="velora-con48-muted">Core tables</div><div class="velora-con48-big">'+esc48(s.core_tables??0)+'/15</div></div><div class="velora-con48-card"><div class="velora-con48-muted">RLS tables</div><div class="velora-con48-big">'+esc48(s.rls_tables??0)+'/15</div></div><div class="velora-con48-card"><div class="velora-con48-muted">Velora RPCs</div><div class="velora-con48-big">'+esc48(s.velora_functions??0)+'</div></div></div><div class="velora-con48-card" style="margin-top:12px"><div class="velora-con48-row"><div><strong>Architecture posture</strong><div class="velora-con48-muted">'+esc48(s.architecture_mode||'pending')+'</div></div>'+pill48(d.status||'pending',(d.status||'').toLowerCase()==='pass'?'velora-con48-pass':(d.status||'').toLowerCase()==='warn'?'velora-con48-warn':'velora-con48-fail')+'</div><div class="velora-con48-muted" style="margin-top:8px">Audit events recorded: '+esc48(s.audit_events??0)+'</div></div><div class="velora-con48-card" style="margin-top:12px"><strong>Findings</strong><div class="velora-con48-list">'+(f.length?f.map(x=>'<div class="velora-con48-finding"><div class="velora-con48-row"><strong>'+esc48(x.code)+'</strong>'+pill48(x.severity,(x.severity||'').toLowerCase()==='critical'?'velora-con48-fail':(x.severity||'').toLowerCase()==='high'?'velora-con48-warn':'')+'</div><div class="velora-con48-muted" style="margin-top:6px">'+esc48(x.message)+'</div></div>').join(''):'<div class="velora-con48-muted">No open consolidation findings.</div>')+'</div></div></div>';
h.querySelector('#con48Run').onclick=async()=>{h.innerHTML='<div class="velora-con48-card">Running system consolidation audit…</div>';const x=await rpc48('velora_run_system_consolidation_audit',{});if(x.error){h.innerHTML='<div class="velora-con48-card"><strong>Audit failed</strong><div class="velora-con48-muted" style="margin-top:6px">'+esc48(x.error.message)+'</div></div>';return}render48()};h.querySelector('#con48Refresh').onclick=render48;
}catch(e){h.innerHTML='<div class="velora-con48-card"><strong>System audit unavailable</strong><div class="velora-con48-muted" style="margin-top:6px">'+esc48(e.message||e)+'</div></div>'}}
function install48(){if(host48())return;const c=document.getElementById('adminContent');if(!c)return;const h=document.createElement('div');h.id='veloraConsolidation48';c.appendChild(h);render48()}
function addNav48(){const nav=document.querySelector('#adminPlatform .admin-nav');if(!nav||nav.querySelector('[data-con48-nav]'))return;const sec=document.createElement('div');sec.className='admin-nav-section';sec.innerHTML='<div class="admin-nav-title">Governance</div><div class="admin-nav-item" data-con48-nav><span>🧩</span><span>System Audit</span></div>';const item=sec.querySelector('[data-con48-nav]');item.onclick=()=>{document.querySelectorAll('.admin-nav-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');const t=document.getElementById('adminHeaderTitle');if(t)t.textContent='System Integration Audit';install48()};nav.appendChild(sec)}
setTimeout(addNav48,1900);setTimeout(install48,2400);window.VELORA_RENDER_SYSTEM_AUDIT48=render48;console.log('✅ Velora Stage 48 System Integration Audit loaded');
})();
